
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: EasyReceipts - Stage-aware stack (Cognito + HttpApi + DynamoDB + S3 pipeline + CloudFront UI) - no circular deps

Parameters:
  AppName:
    Type: String
    Default: easyreceipts

  Env:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]

  UiDomainPrefix:
    Type: String
    Default: easyreceipts-dev-ui
    Description: Cognito Hosted UI domain prefix (must be unique within the region)

  TestsUserPoolClientId:
    Type: String
    Default: ""
    Description: "Cognito app client id used by CLI tests (USER_PASSWORD_AUTH). Leave empty if not used."

  # Decouple Cognito + CORS from CloudFront to avoid circular dependencies
  UiCallbackUrl:
    Type: String
    Default: "http://localhost:8088/callback"
    Description: "Callback URL for Cognito OAuth (dev can be localhost; prod will be updated post-deploy)"

  UiLogoutUrl:
    Type: String
    Default: "http://localhost:8088/"
    Description: "Logout URL for Cognito OAuth (dev can be localhost; prod will be updated post-deploy)"

  UiAllowedOrigins:
    Type: String
    Default: "http://localhost:8088,http://localhost:8080,http://localhost:5173"
    Description: "CORS allowed origins. Use '*' to allow all (temporary). Or comma-separated list."

  # Stripe redirects (success/cancel/portal return). In PROD set this to the CloudFront UI URL.
  AppBaseUrl:
    Type: String
    Default: "http://localhost:8088"
    Description: "Base URL of the app used for Stripe redirect URLs (e.g., https://<cloudfront-domain>). No trailing slash."

Conditions:
  HasTestsClientId: !Not [!Equals [!Ref TestsUserPoolClientId, ""]]
  AllowAllOrigins: !Equals [!Ref UiAllowedOrigins, "*"]

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        APP_NAME: !Ref AppName
        ENV: !Ref Env

Resources:

  # ---------------------------
  # Cognito (Auth)
  # ---------------------------
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AppName}-${Env}-userpool"
      AutoVerifiedAttributes: [email]
      UsernameAttributes: [email]
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub "${AppName}-${Env}-client"
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows: [code]
      AllowedOAuthScopes: [openid, email, profile]
      CallbackURLs:
        - !Ref UiCallbackUrl
      LogoutURLs:
        - !Ref UiLogoutUrl
      SupportedIdentityProviders: [COGNITO]

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref UiDomainPrefix
      UserPoolId: !Ref UserPool

  # ---------------------------
  # DynamoDB
  # ---------------------------
  ReceiptsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AppName}-${Env}-receipts"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  UserTagsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AppName}-${Env}-tags"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  UsageMonthlyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AppName}-${Env}-usage"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  # NEW: Users table for trial + subscription state
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AppName}-${Env}-users"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

  # ---------------------------
  # UI bucket + CloudFront distribution
  # ---------------------------
  UserCategoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: App
          Value: !Ref AppName
        - Key: Env
          Value: !Ref Env

  UiBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppName}-${Env}-ui-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  UiOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${AppName}-${Env}-ui-oai"

  UiBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UiBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt UiOAI.S3CanonicalUserId
            Action: "s3:GetObject"
            Resource: !Sub "${UiBucket.Arn}/*"

  UiDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        Origins:
          - Id: UiS3Origin
            DomainName: !GetAtt UiBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${UiOAI}"
        DefaultCacheBehavior:
          TargetOriginId: UiS3Origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD, OPTIONS]
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100

  # ---------------------------
  # HTTP API + JWT Authorizer (Cognito)
  # ---------------------------
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "${AppName}-${Env}-api"
      CorsConfiguration:
        AllowOrigins: !Split [",", !Ref UiAllowedOrigins]
        AllowHeaders:
          - content-type
          - authorization
        AllowMethods:
          - GET
          - POST
          - PUT
          - OPTIONS
          - DELETE
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"
              audience:
                - !Ref UserPoolClient
                - !If [HasTestsClientId, !Ref TestsUserPoolClientId, !Ref "AWS::NoValue"]
            IdentitySource: $request.header.Authorization

  # ---------------------------
  # API Lambda
  # ---------------------------
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Env}-api"
      CodeUri: src/api/
      Handler: app.handler
      Environment:
        Variables:
          CORS_ORIGINS: !Ref UiAllowedOrigins
          COGNITO_DOMAIN: !Sub "${UiDomainPrefix}.auth.${AWS::Region}.amazoncognito.com"
          COGNITO_CLIENT_ID: !Ref UserPoolClient
          RECEIPTS_TABLE: !Ref ReceiptsTable
          TAGS_TABLE: !Ref UserTagsTable
          USAGE_TABLE: !Ref UsageMonthlyTable
          USERS_TABLE: !Ref UsersTable
          USER_CATEGORIES_TABLE: !Ref UserCategoriesTable
          TRIAL_DAYS: "14"
          UPLOADS_BUCKET: !Sub "${AppName}-${Env}-uploads-${AWS::AccountId}-${AWS::Region}"

          # Stripe config (recommended: SSM dynamic references)
          # NOTE: replace "/spendify/..." with your preferred path if needed
          STRIPE_SECRET_KEY_PARAM: !Sub "/spendify/${Env}/stripe/secret_key"
          STRIPE_PRICE_ID_PARAM: !Sub "/spendify/${Env}/stripe/price_id"
          STRIPE_WEBHOOK_SECRET_PARAM: !Sub "/spendify/${Env}/stripe/webhook_secret"



          # Used by the backend to craft Stripe redirect URLs
          APP_BASE_URL: !Ref AppBaseUrl

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ReceiptsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTagsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsageMonthlyTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserCategoriesTable
        - S3CrudPolicy:
            BucketName: !Sub "${AppName}-${Env}-uploads-${AWS::AccountId}-${AWS::Region}"
        - Statement:
            Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
            Resource:
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/spendify/${Env}/stripe/*"
        - Statement:
            Effect: Allow
            Action:
              - kms:Decrypt
            Resource: "*"

      Events:
        # PUBLIC: OAuth code exchange (no JWT)
        AuthExchangePost:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /auth/exchange
            Method: POST
            Auth:
              Authorizer: NONE

        AuthExchangeOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /auth/exchange
            Method: OPTIONS
            Auth:
              Authorizer: NONE

        # PUBLIC: Stripe webhook (no JWT)
        StripeWebhookPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /webhooks/stripe
            Method: POST
            Auth:
              Authorizer: NONE

        StripeWebhookOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /webhooks/stripe
            Method: OPTIONS
            Auth:
              Authorizer: NONE

        ApiProxyOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: OPTIONS
            Auth:
              Authorizer: NONE

        ApiProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY
            Auth:
              Authorizer: CognitoAuthorizer

        ApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /
            Method: ANY
            Auth:
              Authorizer: CognitoAuthorizer

  # ---------------------------
  # Preprocess Lambda
  # ---------------------------
  PreprocessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Env}-preprocess"
      CodeUri: src/preprocess/
      Handler: app.handler
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          RECEIPTS_TABLE: !Ref ReceiptsTable
          UPLOADS_BUCKET: !Sub "${AppName}-${Env}-uploads-${AWS::AccountId}-${AWS::Region}"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ReceiptsTable
        - S3CrudPolicy:
            BucketName: !Sub "${AppName}-${Env}-uploads-${AWS::AccountId}-${AWS::Region}"

  # ---------------------------
  # OCR Lambda
  # ---------------------------
  OcrFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Env}-ocr"
      CodeUri: src/ocr/
      Handler: app.handler
      Timeout: 120
      MemorySize: 1024
      Environment:
        Variables:
          RECEIPTS_TABLE: !Ref ReceiptsTable
          USAGE_TABLE: !Ref UsageMonthlyTable
          UPLOADS_BUCKET: !Sub "${AppName}-${Env}-uploads-${AWS::AccountId}-${AWS::Region}"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ReceiptsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsageMonthlyTable
        - S3CrudPolicy:
            BucketName: !Sub "${AppName}-${Env}-uploads-${AWS::AccountId}-${AWS::Region}"
        - Statement:
            Effect: Allow
            Action:
              - textract:AnalyzeExpense
              - textract:DetectDocumentText
            Resource: "*"

  # ---------------------------
  # S3 -> Lambda invoke permissions (explicit)
  # NOTE: SourceArn is built with !Sub to avoid depending on UploadsBucket.Arn
  # ---------------------------
  PreprocessInvokePermissionFromS3:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PreprocessFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${AppName}-${Env}-uploads-${AWS::AccountId}-${AWS::Region}"

  OcrInvokePermissionFromS3:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OcrFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${AppName}-${Env}-uploads-${AWS::AccountId}-${AWS::Region}"

  # ---------------------------
  # Uploads bucket (private) for receipts + NotificationConfiguration (explicit)
  # ---------------------------
  UploadsBucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - PreprocessInvokePermissionFromS3
      - OcrInvokePermissionFromS3
    Properties:
      BucketName: !Sub "${AppName}-${Env}-uploads-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: !If
              - AllowAllOrigins
              - ["*"]
              - !Split [",", !Ref UiAllowedOrigins]
            AllowedMethods: ["GET","PUT","POST","HEAD"]
            AllowedHeaders: ["*"]
            ExposedHeaders: ["ETag","x-amz-request-id","x-amz-id-2"]
            MaxAge: 3000
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt PreprocessFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: original/
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt OcrFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: processed/

Outputs:
  ApiUrl:
    Description: HTTP API endpoint
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"

  UiUrl:
    Description: CloudFront UI URL
    Value: !Sub "https://${UiDistribution.DomainName}"

  UiDistributionDomain:
    Value: !GetAtt UiDistribution.DomainName

  UiBucketName:
    Value: !Ref UiBucket

  UploadsBucketName:
    Value: !Ref UploadsBucket

  UsersTableName:
    Value: !Ref UsersTable

  UserCategoriesTableName:
    Description: User categories table name
    Value: !Ref UserCategoriesTable

  CognitoHostedUiIssuer:
    Description: Cognito issuer URL (for JWT)
    Value: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"

  CognitoDomain:
    Description: Hosted UI base domain
    Value: !Sub "https://${UiDomainPrefix}.auth.${AWS::Region}.amazoncognito.com"

  UserPoolId:
    Value: !Ref UserPool

  UserPoolClientId:
    Value: !Ref UserPoolClient
